In [6]:
import numpy
array=numpy.array([1,2,3,4,5],dtype=int)
array

array([1, 2, 3, 4, 5])

In [7]:
import numpy
array=numpy.array([1,2,3,4,5],dtype=float)
array

array([1., 2., 3., 4., 5.])

In [8]:
import numpy as np


In [9]:
#o dimension
arr0=np.array(10)
print(arr0)
print(arr0.ndim)
print(arr0.shape)

10
0
()


In [10]:
#1 dimension
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4 5]
1
(5,)


In [14]:
#2 dimension
arr2=np.array([[1,2,2],[3,4,5]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 2]
 [3 4 5]]
2
(2, 3)


In [16]:
#3 dimension
arr3=np.array([[[1,2,1],[3,4,5]]])
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[1 2 1]
  [3 4 5]]]
3
(1, 2, 3)


In [18]:
#3 dimension
arr4=np.array([[[[1,2,1],[3,4,5]]]])
print(arr4)
print(arr4.ndim)
print(arr4.shape)

[[[[1 2 1]
   [3 4 5]]]]
4
(1, 1, 2, 3)


In [20]:
#2X2
a=np.identity(2,dtype=int)
print("2X2 matrix")
print(a)

2X2 matrix
[[1 0]
 [0 1]]


In [24]:
# 2X3
a0=np.eye(2, 3)
print("2X3 matrix")
print(a0)

2X3 matrix
[[1. 0. 0.]
 [0. 1. 0.]]


In [25]:
#3X3
a1=np.identity(3,dtype=int)
print("3X3 matrix")
print(a1)

3X3 matrix
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [26]:
#4X4
a2=np.identity(4,dtype=int)
print("4X4 matrix")
print(a2)

4X4 matrix
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [27]:
#manual method
m=np.array([[0,0,0,0,0],[0,0,0,0,0]])
print(m)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [30]:
#zeros
z=np.zeros((2,5),dtype=int)
print(z)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [32]:
#full
f=np.full([2,5],0)
print(f)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [33]:
k=np.full([3,5],5)
print(k)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [36]:
e=np.random.randint(0,100,size=25)
print(e)

[56 92 65 18 50 40 49 33 28 22 91 68 93 16 31 86 47 67 29 15  6 94 61 46
 40]


In [37]:
v=np.ones([3,3],dtype=int)
print(v)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [45]:
n=np.full([3,3],1)
print(n)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [48]:
k=np.random.randint(0,100,(2,3))
print(k)

[[32 26 88]
 [13 20 14]]


In [49]:
print(k.reshape(3,2))

[[32 26]
 [88 13]
 [20 14]]


In [62]:
i=np.random.randint(0,1000,50) #(start,end,no.of elements)
print(i)

[300 612 242 456 625  89 198 461 127 685  25 321 215 113 420  41 365 383
 820 456 147 274 789 778 592 670 738 927 792 710 828  92  32 736 287 181
 213 347 485  79 814 380 773 318 376 359 604 119 880 993]


In [59]:
m=np.arange(0,1000,2) #(start, end,skip value(if it is 2 then 1 value will be skipped))
print(m)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214
 216 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250
 252 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286
 288 290 292 294 296 298 300 302 304 306 308 310 312 314 316 318 320 322
 324 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358
 360 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394
 396 398 400 402 404 406 408 410 412 414 416 418 420 422 424 426 428 430
 432 434 436 438 440 442 444 446 448 450 452 454 456 458 460 462 464 466
 468 470 472 474 476 478 480 482 484 486 488 490 49

In [58]:
l=np.random.randint(0,1000,50)
print(l[0:50:2])

[960 943 477 157 237 531 313 608 790 736 676  99 439 488 790 223 463 955
 968 499  91 789 447 270   3]


In [66]:
print(i[:10])

[300 612 242 456 625  89 198 461 127 685]


In [67]:
print(m[:10])

[ 0  2  4  6  8 10 12 14 16 18]


In [68]:
print(m[-10:])

[980 982 984 986 988 990 992 994 996 998]


In [69]:
print(m[10:26])

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [70]:
print(m[22])

44


In [81]:
print(m[:-1])

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214
 216 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250
 252 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286
 288 290 292 294 296 298 300 302 304 306 308 310 312 314 316 318 320 322
 324 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358
 360 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394
 396 398 400 402 404 406 408 410 412 414 416 418 420 422 424 426 428 430
 432 434 436 438 440 442 444 446 448 450 452 454 456 458 460 462 464 466
 468 470 472 474 476 478 480 482 484 486 488 490 49

In [82]:
print(m[-1000:])

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214
 216 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250
 252 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286
 288 290 292 294 296 298 300 302 304 306 308 310 312 314 316 318 320 322
 324 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358
 360 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394
 396 398 400 402 404 406 408 410 412 414 416 418 420 422 424 426 428 430
 432 434 436 438 440 442 444 446 448 450 452 454 456 458 460 462 464 466
 468 470 472 474 476 478 480 482 484 486 488 490 49

In [84]:
print(m[-11:-1])

[978 980 982 984 986 988 990 992 994 996]


In [85]:
q=np.array([1,2,3,4,5])
print(q)

[1 2 3 4 5]


In [86]:
#a.
q=np.append(q,6)
print(q)


[1 2 3 4 5 6]


In [87]:
#b. Insert the element 10 at the beginning of the array.

q=np.insert(q,0,10)
print(q)


[10  1  2  3  4  5  6]


In [88]:
#c. Insert the element 30, before 4

q=np.insert(q,4,30)
print(q)

[10  1  2  3 30  4  5  6]


In [89]:
#d. Update the element 5 as 50.

q[6]=50
print(q)

[10  1  2  3 30  4 50  6]


In [90]:
#e. Delete the element 50 in the updated array.

q=np.delete(q,6)
print(q)

[10  1  2  3 30  4  6]


In [98]:
#f. Create a function to search for the element 30.
for i in q:
    if i==30:
        print(i)

30


In [100]:
#g. Sort the array in ascending order.
print(np.sort(q))
q=np.sort(q)[::-1]
print(q)

[ 1  2  3  4  6 10 30]
[30 10  6  4  3  2  1]
